name: erevive
description: E-Commerce App built in flutter using GetX


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+3 
  animate_do: ^3.1.2
  get: ^4.6.6
  bottom_navy_bar: ^6.0.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  animations: ^2.0.11
  dotted_border: ^2.0.0+1
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/electronic-waste.png"

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/ewaste.png
     - assets/background.png
     - assets/img7.png
     - assets/img12.png
     - assets/img14.png
     - assets/profile_pic.png
     - assets/card-payment.png
     - assets/cash-on-delivery-payment.png
     - assets/electronic-waste.png
     - assets/online-shopping-order-delivery.png
     - assets/ewaste3.png
     - assets/ewast1.png
     - assets/img15.jpg